
name: Push Container to Heroku
env:
  HEROKU_API_KEY: "0feefea8-2afb-444f-816d-bd7d55a7ce17"
  HEROKU_APP_STAGING : "ai-store-test-frontend"
  
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Updating Ubuntu system and Heroku
        env: 
          HEROKU_API_KEY: ${{ env.HEROKU_API_KEY }}
        run: sudo apt update && sudo apt install heroku neofetch
      - name: Checking the info
        run: neofetch

      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_email: iateriam@mail.ru
          heroku_api_key: ${{end.HEROKU_API_KEY}}
          heroku_app_name: iateriam@mail.ru
          branch: HEAD
          useforce: false
          dynamicFiles: false
