
name: Push Container to Heroku
env:
  HEROKU_API_KEY: "0feefea8-2afb-444f-816d-bd7d55a7ce17"
  HEROKU_APP_STAGING : "ai-store-test-frontend"
  
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Push to Heroku
      run: git push -f https://heroku:${{ env.HEROKU_API_KEY }}@git.heroku.com/${{ env.HEROKU_APP_STAGING }}.git origin/main:main
