
name: Push Container to Heroku
env:
  HEROKU_API_KEY: "0feefea8-2afb-444f-816d-bd7d55a7ce17"
  
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ env.HEROKU_API_KEY }}
      run: heroku container:login 
