name: Deploy


on: [push]

      
jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v1
    - name: Push to Heroku
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 
    - name: Push to Heroku
      run: git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_APP_STAGING }}.git origin/main:main
